# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
loom.platform = forge

# Mod properties
mod_version = 1.0.0
maven_group = net.mystic.glowworks
archives_name = glowworks

# Minecraft properties
minecraft_version = 1.20.1

# Dependencies
forge_version = 1.20.1-47.4.10

moonlight_version = 1.20-2.16.15
emi_version = 1.1.22
jei_version = 15.20.0.118
embeddium_version = 0.3.31

mixin_extras_version = 0.4.0