modLoader = "javafml"
loaderVersion = "[47,)"

[[mods]]
modId = "glowworks"
version = "${version}"
displayName = "Glowworks"
logoFile = "logo.png"
authors = "Xel'Bayria"
credits = ""
description = '''
An addon for Colorful-Lighting and is a helper mod.
'''
modUrl = "https://www.curseforge.com/minecraft/mc-mods/glowworks"
issueTrackerURL = "https://github.com/Xelbayria/Glowworks/issues"
license = "Supplementaries Team License v.1.1"

[[dependencies.glowworks]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.glowworks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.glowworks]]
modId="colorful_lighting"
mandatory=true
versionRange="[1.20.1-1.8.3,]"
ordering="NONE"
side="BOTH"

[[dependencies.glowworks]]
modId="moonlight"
mandatory=true
versionRange="[1.20-2.16.0,]"
ordering="NONE"
side="BOTH"