modLoader = "javafml"
loaderVersion = "[47,)"

license = "${mod_license}"
issueTrackerURL = "${mod_github}/issues"

[[mods]]
modId = "glowworks"
version = "${version}"
displayName = "Glowworks"
logoFile = "logo.png"
authors = "${mod_authors}"
credits = "${mod_credits}"
description = '''${mod_description}'''
modUrl = "${mod_homepage}"

[[dependencies.glowworks]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.glowworks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.glowworks]]
modId="colorful_lighting"
mandatory=true
versionRange="[1.20.1-1.8.3,]"
ordering="NONE"
side="BOTH"

[[dependencies.glowworks]]
modId="moonlight"
mandatory=true
versionRange="[1.20-2.16.0,]"
ordering="NONE"
side="BOTH"