modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "glowworks"
version = "${version}"
displayName = "Glowworks"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.glowworks]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.glowworks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.glowworks]]
modId="colorful_lighting"
mandatory=true
versionRange="[1.20.1-1.8.3,]"
ordering="NONE"
side="BOTH"

[[dependencies.glowworks]]
modId="moonlight"
mandatory=true
versionRange="[1.20-2.16.0,]"
ordering="NONE"
side="BOTH"